version: '3.4'

services:
    siremudb:
        build:
            context: .
            dockerfile: ./database/Dockerfile
        ports:
            - "1443:1433"
        volumes:
            - sqlvolume:/var/opt/mssql

    siremuservercanciones:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        command: cd /usr/home/ServidorCanciones/
        command: mvn exec:java -Dexec.mainClass="com.servidorcanciones.ServidorCanciones"
        ports:
            - "25112:25112"
        volumes:
            - /usr/src/

    siremuserverlistas:
        build:
            context: .
            dockerfile: ./backend2/Dockerfile
        command: cd /usr/home/ServidorListas
        command: ruby servidor_listas.rb &
        ports:
            - "25111:25111"
        volumes:
            - /usr/src/

    siremuservercuentas:
        build:
            context: .
            dockerfile: ./backend3/Dockerfile
        command: ruby /usr/home/ServidorCuentas/servidor_cuentas.rb &
        ports:
            - "25113:25113"
        volumes:
            - /usr/src/
            
volumes:
    sqlvolume: