# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: manejoListas.proto for package 'mnjListas'

require 'grpc'
require_relative 'manejoListas_pb'

module MnjListas
  module ManejoListas
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mnjListas.ManejoListas'

      rpc :AgregarQuitarCancionesLista, MnjListas::ListaAA, MnjListas::RespuestaListas
      rpc :AgregarListaAMeGusta, MnjListas::ListaAA, MnjListas::RespuestaListas
      rpc :BuscarListas, MnjListas::NombreLista, MnjListas::ListaListas
      rpc :ConsultarMisListas, MnjListas::IdUsuario, MnjListas::ListaListas
      rpc :ConsultarMisListasAgregadas, MnjListas::IdUsuario, MnjListas::ListaListas
      rpc :ConsultarMisListasDefault, MnjListas::IdUsuario, MnjListas::ListaListas
      rpc :CrearListaReproduccion, MnjListas::ListaAG, MnjListas::RespuestaListas
      rpc :ModificarListaReproduccion, MnjListas::ListaAG, MnjListas::RespuestaListas
      rpc :EliminarListaReproduccion, MnjListas::ListaAG, MnjListas::RespuestaListas
    end

    Stub = Service.rpc_stub_class
  end
end
